Use separator for specifying command

diff --git a/kubectl-node_shell b/kubectl-node_shell
--- a/kubectl-node_shell
+++ b/kubectl-node_shell
@@ -39,18 +39,27 @@ while [ $# -gt 0 ]; do
     namespace="--namespace=${key##*=}"
     shift
     ;;
+  --)
+    shift
+    break
+    ;;
   *)
     if [ -z "$node" ]; then
       node="$1"
+      shift
     else
-      cmd+="\"$1\", "
-      custom=true
+      echo "exactly one node required"
+      exit 1
     fi
-    shift
     ;;
   esac
 done
 
+while [ $# -gt 0 ]; do
+  cmd+="\"$1\", "
+  custom=true
+  shift
+done
 if [ "$custom" = true ]; then
   cmd="$(echo "$cmd" | awk '1' RS=', \n') ]"
 else
